# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa14b406fe440d3a574830d876ec5292924ae6c42597283a15aca5a92dab655b75f8e3e03fba1d467df5e7850ba2488e7b9128928a677d30a60ddf152083ddff

test:
  secret_key_base: 787b89dae587b01f72d1ac432a02617bcea7003471b699aa38a46e5e133c43c3ea9b3e924bcd728b742a001636f16c3477f3a9cf6e16e00538b29a4dccca7d1c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
